import { useMemo, useState } from 'react';
import { Alert, Badge, Button, Card, KeyValueList, PageHeader, TextInput } from '@markorbit/ui';
import {
  createKnowledgeOperatorRunClient,
  KnowledgeOperatorRunHttpError,
  type KnowledgeOperatorRunClient,
  type KnowledgeOperatorRunReceipt
} from '../../api/knowledge-operator-runs.js';

function errorMessage(error: unknown) {
  if (error instanceof KnowledgeOperatorRunHttpError)
    return `${error.status} ${error.code}: ${error.message}`;
  return error instanceof Error ? error.message : 'Knowledge operator run dispatch failed.';
}

export function KnowledgeRunDispatch({
  workspaceId,
  client
}: {
  workspaceId: string;
  client?: KnowledgeOperatorRunClient;
}) {
  const resolvedClient = useMemo(
    () => client ?? createKnowledgeOperatorRunClient(workspaceId),
    [client, workspaceId]
  );
  const [planId, setPlanId] = useState('');
  const [idempotencyKey, setIdempotencyKey] = useState('');
  const [dispatching, setDispatching] = useState(false);
  const [receipt, setReceipt] = useState<KnowledgeOperatorRunReceipt>();
  const [error, setError] = useState('');
  const valid = Boolean(planId.trim() && idempotencyKey.trim() && workspaceId);

  const dispatch = async () => {
    if (!valid || dispatching) return;
    setDispatching(true);
    setReceipt(undefined);
    setError('');
    try {
      setReceipt(
        await resolvedClient.dispatch({
          planId: planId.trim(),
          idempotencyKey: idempotencyKey.trim()
        })
      );
    } catch (cause) {
      setError(errorMessage(cause));
    } finally {
      setDispatching(false);
    }
  };

  return (
    <section aria-label="Knowledge run dispatch">
      <PageHeader
        title="Knowledge Run Dispatch"
        description="Start one governed Knowledge collection run through the authenticated Core bridge"
        actions={<Badge>execution:manage required</Badge>}
      />
      <Alert tone="info" title="Stable idempotency is required">
        The supplied key is sent unchanged. Reusing the same key and plan returns the durable prior
        receipt; reusing it for different input fails closed. This surface does not create Sources,
        Plans or Workers.
      </Alert>
      <Card>
        <h2>Dispatch request</h2>
        <KeyValueList items={[{ key: 'Workspace', value: workspaceId }]} />
        <TextInput
          label="Plan ID"
          value={planId}
          placeholder="pln_…"
          hint="Existing governed Knowledge Plan identity."
          onChange={(event) => setPlanId(event.target.value)}
        />
        <TextInput
          label="Idempotency key"
          value={idempotencyKey}
          placeholder="stable-operator-run-key"
          hint="Use one deliberate stable key for this exact dispatch. It is never generated by the UI."
          onChange={(event) => setIdempotencyKey(event.target.value)}
        />
        <Button disabled={!valid || dispatching} onClick={() => void dispatch()}>
          {dispatching ? 'Dispatching…' : 'Dispatch governed run'}
        </Button>
      </Card>
      {error ? (
        <Alert tone="danger" title="Run was not dispatched">
          {error}
        </Alert>
      ) : null}
      {receipt ? (
        <Alert
          tone="success"
          title={receipt.replayed ? 'Existing durable run returned' : 'Run dispatched'}
        >
          <KeyValueList
            items={[
              { key: 'Run ID', value: receipt.record.run.id },
              { key: 'Replay', value: receipt.replayed ? 'Yes' : 'No' },
              ...(receipt.record.job ? [{ key: 'Job ID', value: receipt.record.job.id }] : []),
              ...(receipt.record.execution
                ? [{ key: 'Execution ID', value: receipt.record.execution.id }]
                : [])
            ]}
          />
        </Alert>
      ) : null}
    </section>
  );
}
