// Generated once for the bounded Super Admin V2 fixture copy; no runtime translation service is used.
export const GENERATED_EN_US = {
  '+12 本月': '+12 this month',
  '0 个值可见': '0 values visible',
  '1 个 Workspace 受影响': '1 Workspace affected',
  '1 分钟前': '1 minute ago',
  '1 天前': '1 day ago',
  '1 将到期': '1 will expire',
  '1 小时前': '1 hour ago',
  '1 条降级': '1 downgrade',
  '1,228 次 rate limited': '1,228 times rate limited',
  '10:18 · 转换完成 · worker-convert-07': '10:18 · Conversion completed · worker-convert-07',
  '10:22 · 自动 locator 校验通过': '10:22 · Automatic locator verification passed',
  '11 分钟前': '11 minutes ago',
  '12 个模型路由引用': '12 model routing references',
  '12 个运行中': '12 running',
  '12 分钟': '12 minutes',
  '12 分钟前': '12 minutes ago',
  '12 分钟前 · CN': '12 minutes ago · CN',
  '12 秒前': '12 seconds ago',
  '12 进行中': '12 in progress',
  '12 需关注': '12 need attention',
  '12,842 个文件': '12,842 files',
  '17 分钟前': '17 minutes ago',
  '18 分钟': '18 minutes',
  '18 分钟前': '18 minutes ago',
  '18 分钟前 · Global': '18 minutes ago · Global',
  '18 小时': '18 hours',
  '18 待审核': '18 Pending review',
  '18 条待审核': '18 items to be reviewed',
  '18 条证据等待审核': '18 pieces of evidence awaiting review',
  '2 个 Ready Package': '2 Ready Packages',
  '2 个 Ready Package 等待新版本': '2 Ready Packages waiting for new versions',
  '2 个有降级': '2 downgraded',
  '2 个未建模': '2 unmodeled',
  '2 个部分可用': '2 sections available',
  '2 个降级': '2 downgrades',
  '2 个需处理': '2 need to be processed',
  '2 个高优先级': '2 high priority',
  '2 个高影响': '2 high impact',
  '2 分钟前': '2 minutes ago',
  '2 天前': '2 days ago',
  '2 小时前': '2 hours ago',
  '2 待审核': '2 Pending review',
  '2 运行中': '2 Running',
  '2012–至今': '2012–present',
  '2026.09 · 4 小时前验证': '2026.09 · Verified 4 hours ago',
  '24 已开启': '24 turned on',
  '26 分钟前': '26 minutes ago',
  '28 已接纳': '28 Accepted',
  '28 秒前': '28 seconds ago',
  '3 个 webhook endpoints': '3 webhook endpoints',
  '3 个今日到期': '3 expire today',
  '3 个候选': '3 candidates',
  '3 个待审核': '3 pending review',
  '3 个有效租约': '3 valid leases',
  '3 个繁忙': '3 busy',
  '3 个需关注': '3 need attention',
  '3 个需复核': '3 need to be reviewed',
  '3 个高优先级': '3 high priority',
  '3 分钟前': '3 minutes ago',
  '3 天': '3 days',
  '3 套餐': '3 packages',
  '3 小时前': '3 hours ago',
  '3 类能力': 'Type 3 abilities',
  '3 项需要人工复核': '3 items require manual review',
  '30 天内': 'Within 30 days',
  '30 天内到期': 'Expires within 30 days',
  '32 次 fallback': '32 fallbacks',
  '32 次调用改用备用模型': '32 calls to alternate model',
  '38 分钟前': '38 minutes ago',
  '4 个 URL 等待': '4 URLs waiting',
  '4 个司法辖区': '4 jurisdictions',
  '4 个层级': '4 levels',
  '4 个待交付': '4 to be delivered',
  '4 个待关注': '4 to follow',
  '4 个核心域': '4 core domains',
  '4 个核心服务': '4 core services',
  '4 个能力池': '4 ability pools',
  '4 个评估中': '4 under evaluation',
  '4 个高优先级': '4 high priority',
  '4 分钟前': '4 minutes ago',
  '4 小时内': 'within 4 hours',
  '4 小时前': '4 hours ago',
  '4 已配置': '4 configured',
  '4 待交付': '4 To be delivered',
  '4 类资源': '4 types of resources',
  '43 正常': '43 Normal',
  '48 个连接': '48 connections',
  '48 小时内': 'Within 48 hours',
  '5 分钟前 · 3 次': '5 minutes ago · 3 times',
  '6 个 owner': '6 owners',
  '6 个产品': '6 products',
  '6 个能力域': '6 capability domains',
  '6 个队列': '6 queues',
  '6 个需刷新': '6 need to be refreshed',
  '6 分钟前': '6 minutes ago',
  '6 小时前': '6 hours ago',
  '7 个 owner': '7 owners',
  '7 个 trace': '7 traces',
  '7 分钟': '7 minutes',
  '7 天后到期': 'Expires in 7 days',
  '8 个 Workspace 连接': '8 Workspace connections',
  '8 个 owner': '8 owners',
  '8 分钟前': '8 minutes ago',
  '8 分钟前 · EUIPO': '8 minutes ago · EUIPO',
  '9 分钟前': '9 minutes ago',
  '9 秒前': '9 seconds ago',
  '90 天': '90 days',
  '96% 当前': '96% currently',
  '96% 新鲜': '96% fresh',
  '98.6% 成功': '98.6% successful',
  '98.7% 可用': '98.7% available',
  '99.2% owner 成功': '99.2% owner successful',
  'A/B 中': 'A/B medium',
  'AI 模型服务': 'AI model service',
  'AI 调用': 'AI call',
  'API 启停策略': 'API start and stop strategy',
  'API 开关': 'API switch',
  'API 调用': 'API call',
  'API 连接': 'API connection',
  'API 限流策略更新': 'API current limiting policy update',
  'Acme IP · Scale 月度订阅': 'Acme IP · Scale Monthly Subscription',
  'Acme IP 已使用 92%': 'Acme IP 92% used',
  'Agent 是受治理实现，调用 Capability、Skill 与工具；不拥有正式业务状态。':
    'Agent is a governed implementation that calls capabilities, skills, and tools; it does not have a formal business state.',
  'Brain 执行': 'Brain execution',
  'Brain 路由和模型输出不是正式业务状态；Capability 调用保留 canonical ID。':
    'Brain routing and model outputs are not official business states; Capability calls retain canonical IDs.',
  'Brain 运行总览': 'Brain running overview',
  'CN · 公告与状态数据包': 'CN · Announcement and status packet',
  'CNIPA 公告增量': 'CNIPA Announcement Increment',
  'CNIPA 公告采集': 'CNIPA announcement collection',
  'CNIPA 增量等待 plan approval': 'CNIPA incremental waiting for plan approval',
  'CNIPA 审查指南 · 第三章 §2.4': 'CNIPA Review Guidelines · Chapter 3 §2.4',
  'CNIPA 数据包构建': 'CNIPA data package construction',
  'CNIPA 数据包重放': 'CNIPA packet replay',
  'CNIPA 数据包重放待审核': 'CNIPA packet replay pending review',
  'Capability 节点': 'Capability node',
  'Capability 调用': 'Capability call',
  'CollectionRun 创建': 'CollectionRun Create',
  'Data Engine CN 批次等待批准': 'Data Engine CN batch awaiting approval',
  'Data Engine 真实摘要': 'Data Engine Real Summary',
  'Data Engine 系统设置': 'Data Engine system settings',
  'Demo fixture · 不代表实时 owner truth':
    'Demo fixture · Does not represent real-time owner truth',
  'Demo 中未执行': 'Not implemented in Demo',
  'Demo 反馈': 'Demo feedback',
  'Demo 评审工具': 'Demo review tool',
  'EU · 商标与异议数据': 'EU · Trademark and Opposition Data',
  'EUIPO 公告源延迟超过演示阈值': 'EUIPO announcement source delay exceeds demonstration threshold',
  'EUIPO 商标回填': 'EUIPO trademark backfill',
  'EUIPO 指南监测': 'EUIPO Guidelines Monitoring',
  'EUIPO 指南采集': 'EUIPO Guide Collection',
  'EUIPO 新鲜度低于目标': 'EUIPO freshness is lower than target',
  'Fallback 就绪': 'Fallback ready',
  'Fallback 成本': 'Fallback cost',
  'Gateway 同时校验 Knowledge read capability 与 Workspace membership。':
    'Gateway simultaneously verifies Knowledge read capability and Workspace membership.',
  'Global Brand · MarkReg 服务': 'Global Brand · MarkReg Service',
  'Global · 国际注册': 'Global · International Registration',
  'Job snapshot 冻结': 'Job snapshot frozen',
  'Knowledge 来源新鲜度下降': 'Knowledge source freshness decreased',
  'Knowledge 真实摘要': 'Knowledge true summary',
  'Knowledge 读取授权检查': 'Knowledge read authorization check',
  'Locator 与原文一致；保留适用范围限定。':
    'Locator is consistent with the original text; retains the scope of application.',
  'MFA 已启用': 'MFA enabled',
  'MFA 缺失': 'MFA missing',
  'Manifest 可追溯': 'Manifest traceable',
  'Manifest 已冻结': 'Manifest frozen',
  'Manifest 未冻结': 'Manifest not frozen',
  'OA 分析与答复': 'OA analysis and reply',
  'OpenAI 路由进入降级链': 'OpenAI routing enters the downgrade chain',
  'Owner / 来源': 'Owner / Source',
  'Owner projection 连接失败 fixture': 'Owner projection connection failed fixture',
  'Owner 任务、执行、Worker、日志与受控恢复':
    'Owner tasks, execution, workers, logs and controlled recovery',
  'Owner 健康': 'Owner Health',
  'Owner 审批': 'Owner approval',
  'Owner 成功返回 0 个 target；这是有效空状态，不是读取失败。':
    'Owner successfully returns 0 targets; this is a valid empty state, not a read failure.',
  'Owner 投影': 'Owner projection',
  'Owner 暂不可用': 'Owner is currently unavailable',
  'Owner 校验': 'Owner verification',
  'Owner 检查中': 'Owner Checking',
  'Owner 正常': 'Owner Normal',
  'Owner 筛选': 'Owner filter',
  'Owner 管理': 'Owner management',
  'Owner 读取不可用。': 'Owner read is not available.',
  'Owner 调度': 'Owner Scheduling',
  'Owner 返回语义': 'Owner return semantics',
  'P95 延迟': 'P95 delay',
  'P95 时长': 'P95 Duration',
  'Plan Scale 提供权益': 'Plan Scale provides benefits',
  'Primary 健康': 'Primary health',
  'Prompt 版本': 'Prompt version',
  'Provider quota 阻断': 'Provider quota blocking',
  'Ready Package 生成': 'Ready Package generation',
  'Real 模式不会使用 Demo fixture 填补缺失数据，也不会直接访问 owner 数据库。':
    'Real mode does not use the Demo fixture to fill in missing data, nor does it directly access the owner database.',
  'Reflection Candidate 与任务完成都不是 Capability canonical truth 或自动验证。':
    'Reflection Candidate and task completion are not Capability canonical truth or automatic verification.',
  'Route 正常': 'Route Normal',
  'SLA 内': 'Within SLA',
  'SLO 风险': 'SLO Risk',
  'SMS 改走 Email': 'SMS changed to Email',
  'Skill 是 Capability 的受治理实现组成，不等于 Capability 本身。':
    'Skill is a managed implementation component of Capability and is not equal to Capability itself.',
  'Stripe webhook 延迟': 'Stripe webhook delay',
  'Sunrise Trading · 争议': 'Sunrise Trading · Controversy',
  'Trading 部分可用': 'Trading section available',
  'US package 校验完成': 'US package verification completed',
  'US · 商标档案与事件': 'US · Trademark Archives and Events',
  'USPTO OA 索引': 'USPTO OA Index',
  'USPTO TSDR 同步': 'USPTO TSDR synchronization',
  'USPTO 手册扫描': 'USPTO manual scan',
  'WIPO Madrid 解析': 'WIPO Madrid Analysis',
  'WIPO parser 连续失败 3 次': 'WIPO parser failed 3 times in a row',
  'WIPO 转换连续失败': 'WIPO conversion fails continuously',
  'Webhook 延迟': 'Webhook delay',
  'Webhook 延迟 11 分钟': 'Webhook delayed by 11 minutes',
  'Worker lease 获取': 'Worker lease acquisition',
  'Workspace 分配': 'Workspace allocation',
  'Workspace 启用': 'Workspace enabled',
  'Workspace 审计': 'Workspace Audit',
  'Workspace 审计事件': 'Workspace audit events',
  'Workspace 授权': 'Workspace authorization',
  'Workspace 未启用': 'Workspace is not enabled',
  'Workspace 目录': 'Workspace directory',
  'Workspace 管理': 'Workspace Management',
  'Workspace 配置': 'Workspace configuration',
  'Workspace 配额接近上限': 'Workspace quota is approaching the upper limit',
  'lease 还有 4m': 'lease 4m left',
  '· 本地确定性 fixture': '· Local deterministic fixture',
  '· 演示对象': '· Demonstration object',
  '↻ 模拟刷新': '↻ Simulation refresh',
  一: 'One',
  '一 21': '1 21',
  三: 'Three',
  '三 23': 'Three 23',
  上传原始文件: 'Upload the original file',
  上架: 'On the shelves',
  上游版本不一致: 'The upstream version is inconsistent',
  下一步: 'Next step',
  '下次 2 小时后': 'Next time in 2 hours',
  '下次 20 小时后': 'Next time in 20 hours',
  不代表履约: 'does not represent performance of the contract',
  不会写入任何服务或数据库: 'will not write to any service or database',
  '不会改变正式状态、付款、能力验证或 Official Truth':
    'Does not alter official status, payment, proficiency verification, or Official Truth',
  不会自动出队: 'will not automatically leave the queue',
  不参与供应: 'Does not participate in supply',
  不参与采集: 'Do not participate in collection',
  不可变: 'immutable',
  '不可变 Demo 原件；选择不会替换或写入 owner 存储。':
    'Immutable Demo original; selection will not replace or write to owner storage.',
  不可变对象: 'Immutable object',
  不可变库存: 'Immutable inventory',
  不可用: 'Not available',
  '不可由 Core 推断': 'cannot be inferred from Core',
  不可越权推进: 'Cannot advance beyond the authority',
  不可进入审核: 'cannot enter the review',
  不可重试: 'No retry possible',
  '不含 ledger mutation': 'does not contain ledger mutation',
  不含不可用源: 'does not contain unavailable sources',
  不含未建模: 'does not include unmodeled',
  不在此对象: 'is not in this object',
  不执行删除: 'Do not perform deletion',
  不接收任务: 'Do not accept tasks',
  不推断: 'Do not infer',
  不由付款推断: 'Not inferred from payment',
  '不等于 Official Truth': 'is not equal to Official Truth',
  不等于业务接受: 'does not equal business acceptance',
  不等于成员: 'is not equal to members',
  不纳入健康率: 'Not included in health rate',
  不自动停权: 'No automatic suspension',
  不计为零: 'does not count as zero',
  不适用: 'Not applicable',
  不限: 'No limit',
  '专业人士 AI 工作台': 'AI workbench for professionals',
  '专业商标代理机构 · Singapore': 'Professional trademark agency · Singapore',
  '两个 owner 独立读取；任一来源失败不会被解释为零数据，也不会遮蔽另一来源。':
    'Both owners read independently; failure of either source is not interpreted as zero data, nor does it obscure the other source.',
  严格只读: 'Strictly read-only',
  中: 'in',
  主体: 'Subject',
  争议案件: 'Controversial cases',
  事件: 'event',
  事件时间: 'Event time',
  二: 'two',
  '二 22': 'Two 22',
  五: 'five',
  '五 25': 'Five 25',
  产品: 'Products',
  '产品、模块、权益与发布状态分层管理':
    'Hierarchical management of products, modules, rights and release status',
  产品启用: 'Product Enablement',
  产品启用关系: 'Product enablement relationship',
  产品总览: 'Product Overview',
  产品用量: 'Product dosage',
  产品管理: 'Product Management',
  '产品评审：检查受保护操作的确认路径':
    'Product Review: Check the confirmation path for protected operations',
  产品面: 'Product side',
  人工处理: 'Manual processing',
  人工复核: 'Manual review',
  '仅展示凭证引用、轮换和作用域，不回显 secret 值。':
    'Only displays the credential reference, rotation and scope, and does not return the secret value.',
  仅当前版本: 'Current version only',
  仅显示状态: 'Show status only',
  今天: 'Today',
  '今天 06:15': 'Today 06:15',
  '今天 08:15': 'Today 08:15',
  '今天 08:40': 'Today 08:40',
  '今天 08:45': 'Today 08:45',
  '今天 09:18': 'Today 09:18',
  '今天 09:42': 'Today 09:42',
  '今天 10:24': 'Today 10:24',
  今日事件: 'Today’s events',
  今日到期: 'Expires today',
  今日完成: 'Completed today',
  今日审计: 'Audit Today',
  今日执行: 'Execution today',
  今日批准: 'Approved today',
  今日批次: 'Today’s batch',
  今日流水线: 'Today’s assembly line',
  今日登录: 'Log in today',
  今日窗口: 'Today window',
  今日证据: 'Today’s evidence',
  今日调用: 'Call today',
  今日运行: 'Run today',
  仍可部分服务: 'Some services are still available',
  '从 owner 告警进入服务、依赖和任务证据；聚合层只编排调查，不重写 owner 状态。':
    'Enter service, dependency and task evidence from owner alarm; the aggregation layer only orchestrates investigations and does not rewrite owner status.',
  '从国家、对象类型和时间范围识别真实缺口，并保留每格的新鲜度来源。':
    'Identifies real gaps from country, object type, and time frame, and preserves the source of freshness for each grid.',
  从未: 'Never',
  '从来源到 Ready Package 追踪产物、证据与交付，不把供应商回传当作正式真相。':
    'Track products, evidence and delivery from source to Ready Package, and do not treat supplier feedback as official truth.',
  从检查点恢复: 'Restore from checkpoint',
  '从身份进入 MFA、会话、设备和风险事件；风险动作必须精确授权。':
    'Enter MFA from identities, sessions, devices, and risk events; risk actions must be precisely authorized.',
  付款待确认: 'Payment pending confirmation',
  '代理机构 · United Kingdom': 'Agency · United Kingdom',
  '以全局身份为入口查看 Workspace Membership、角色和安全状态，不复制 Workspace 真相。':
    'Use the global identity as the entry point to view Workspace Membership, roles, and security status without duplicating the Workspace truth.',
  '以冻结计划、单次审批、检查点和可恢复日志管理 owner 任务；演示不会派发真实运行。':
    'Manage owner tasks with frozen schedules, single approvals, checkpoints, and recoverable logs; the demo will not dispatch a real run.',
  '以控制项、适用范围、证据、缺口和复核周期管理合规，不用徽章替代证据。':
    'Manage compliance with controls, scope of application, evidence, gaps and review cycles, without using badges as a substitute for evidence.',
  '以输入资格、转换 profile、Worker 租约和输出 receipt 形成可重放的转换账本。':
    'Form a replayable conversion ledger with input qualifications, conversion profile, Worker lease and output receipt.',
  任务与调度: 'Task and Scheduling',
  任务与调度中心: 'Task and Scheduling Center',
  任务总览: 'Task Overview',
  任务流水与检查点: 'Task pipeline and checkpoints',
  任务运行: 'Task running',
  任务运行总览: 'Task running overview',
  任务队列: 'Task queue',
  '企业法务 · China': 'Corporate Legal Affairs · China',
  会话: 'Session',
  估算成本: 'Estimated cost',
  估算用量: 'Estimated usage',
  低: 'Low',
  作废: 'void',
  使用上限: 'Usage limit',
  使用情况: 'Usage',
  '使用版本化评估集验证结果契约、实现和 Critic，不从任务完成自动验证 Capability。':
    'Use versioned evaluation sets to verify result contracts, implementations, and critics without automatically verifying Capability from task completion.',
  使用统计: 'Usage statistics',
  使用量流: 'Usage flow',
  '例如：非显著性标志的整体判断': 'For example: overall judgment of non-distinctive signs',
  供应健康: 'Supply health',
  供应链关注项: 'Supply chain concerns',
  供应链暂停在转换阶段: 'Supply chain paused in transition phase',
  依赖受限: 'Limited dependencies',
  '保护 provider 与预算': 'Protect providers and budgets',
  保持上下文: 'Keep context',
  保留: 'Reserved',
  保留关系: 'Preserve relationship',
  保留审计: 'Retain audit',
  保留策略: 'Retention policy',
  保留谱系: 'Keep the pedigree',
  保留部分状态: 'Keep part of the state',
  候选版本: 'Candidate version',
  停止派发: 'Stop distribution',
  健康: 'Health',
  健康异常: 'Health abnormality',
  '健康来自 owner 投影；未连接、无权限和无数据分别显示。':
    'Health comes from the owner projection; unconnected, no permissions and no data are shown separately.',
  健康监测: 'Health monitoring',
  健康节点: 'Healthy node',
  健康连接: 'Healthy connection',
  允许列表: 'Allow list',
  '先修复转换 profile': 'Fix the conversion profile first',
  全局: 'Global',
  '全局 / 12 Workspace': 'Global / 12 Workspace',
  全局一级导航: 'Global first-level navigation',
  全局允许: 'Globally allowed',
  全局发布: 'Global release',
  全局可用: 'Available globally',
  全局可用策略: 'Globally available strategies',
  全局开关: 'Global switch',
  全局模块: 'Global module',
  全局策略: 'Global strategy',
  '全局策略、产品权益、Workspace 配置和连接健康分层展示，任何一层都不等于其他层。':
    'Global policies, product rights, Workspace configuration and connection health are displayed in layers, and no layer is equal to other layers.',
  全球: 'Global',
  '全球数据覆盖、流水线、质量与受控恢复':
    'Global data coverage, pipeline, quality and controlled recovery',
  全部: 'All',
  '全部 MFA': 'All MFA',
  '全部 Owner': 'All Owner',
  '全部 Workspace': 'All Workspaces',
  全部已隔离: 'All quarantined',
  全部批准状态: 'All approval status',
  全部状态: 'All status',
  全部用户: 'All users',
  全部类型: 'All types',
  全部质量状态: 'All quality status',
  全部集成: 'Integrate all',
  全量快照: 'Full snapshot',
  公告: 'Announcement',
  公告条目: 'Announcement entry',
  六: 'Six',
  '六 26': 'Six 26',
  关系: 'Relationship',
  关系独立: 'Relationship independence',
  关系边: 'Relationship edge',
  '关联 Brain': 'Associate Brain',
  '关联 CollectionRun、Job snapshot、Worker lease 和交付 receipt，失败按阶段隔离。':
    'Associate CollectionRun, Job snapshot, Worker lease and delivery receipt, and failure is isolated by stage.',
  '关联组织、成员、套餐、资源和产品变更，记录 actor、原因和版本。':
    'Associate organization, members, packages, resources, and product changes, recording actors, reasons, and versions.',
  '关联身份、会话、设备、地理信号、策略命中和处置 receipt。':
    'Correlate identities, sessions, devices, geographic signals, policy hits, and disposition receipts.',
  关联运行: 'Associated operation',
  关联链路: 'Associated links',
  关闭: 'Close',
  '关闭 Demo 反馈': 'Close Demo feedback',
  关闭导航: 'Close navigation',
  关闭详情: 'Close details',
  其他: 'Others',
  其他模块正常: 'Other modules are normal',
  '兼容 profile': 'compatible profile',
  内容: 'Content',
  内容范围: 'Content scope',
  内部文件: 'Internal documents',
  写入已限制: 'Writing is restricted',
  写操作: 'Write operation',
  冲突: 'Conflict',
  冲突候选: 'Conflict candidates',
  冻结计划: 'Freeze plan',
  冻结计划待确认: 'Freeze plan to be confirmed',
  准确: 'Accurate',
  凭证: 'Certificate',
  '凭证失败，限流非根因': 'Credential failure, current limiting is not the root cause',
  凭证将到期: 'The voucher will expire',
  凭证引用: 'Credential reference',
  凭证状态: 'Certificate status',
  '分别呈现发布状态、全局可用性、权益覆盖、Workspace 启用和 owner 健康。':
    'Presents release status, global availability, equity coverage, Workspace activation and owner health respectively.',
  '分别展示套餐上限、Workspace 分配、已使用和保留量；调整需要版本检查。':
    'Display the package limit, Workspace allocation, used and reserved amounts respectively; adjustment requires version check.',
  分批发布: 'Release in batches',
  分派所选事项: 'Assign selected items',
  分类: 'Classification',
  列表: 'List',
  刚刚: 'Just now',
  '创建 Agent candidate': 'Create Agent candidate',
  '创建 Capability candidate': 'Create Capability candidate',
  '创建 Data Engine 任务': 'Create Data Engine tasks',
  '创建 Prompt 候选': 'Create Prompt candidate',
  '创建 Ready Package': 'Create Ready Package',
  '创建 Skill candidate': 'Create Skill candidate',
  '创建 Workspace 草案': 'Create Workspace Draft',
  创建争议响应草案: 'Create a draft dispute response',
  创建产品发布草案: 'Create a product release draft',
  创建内部用户邀请: 'Create internal user invitation',
  创建功能配置草案: 'Create feature configuration draft',
  创建发布候选: 'Create release candidates',
  创建发票申请: 'Create an invoice request',
  创建套餐版本草案: 'Create a draft package version',
  创建安全调查: 'Create a security investigation',
  创建整改计划: 'Create a rectification plan',
  '创建新版本 candidate': 'Create new version candidate',
  创建权益版本草案: 'Create draft entitlement version',
  创建站点草案: 'Create a draft site',
  '创建策略 candidate': 'Create strategy candidate',
  创建编排草案: 'Create a layout draft',
  创建者: 'Creator',
  创建角色草案: 'Create a draft character',
  创建订单调整申请: 'Create order adjustment request',
  创建调度变更申请: 'Create a scheduling change request',
  '创建跨 owner 调查': 'Create cross-owner survey',
  创建邀请: 'Create invitation',
  创建采集计划: 'Create a collection plan',
  创建集成故障调查: 'Create an integration failure investigation',
  '判断标志是否发挥来源识别功能并保留实际使用语境。':
    'Determine whether the mark performs the source identification function and retains the actual context of use.',
  到期: 'Expires',
  '到期 2026-12-18': 'Expires 2026-12-18',
  '刷新 RUN-9821 owner receipt': 'Refresh RUN-9821 owner receipt',
  '刷新 owner 快照': 'Refresh owner snapshot',
  '刷新 receipt': 'Refresh receipt',
  刷新任务快照: 'Refresh task snapshot',
  刷新只读摘要: 'Refresh read-only summary',
  '刷新当前 fixture 快照': 'Refresh the current fixture snapshot',
  '剩余 18 天': '18 days remaining',
  功能: 'function',
  '功能定义、发布阶段和允许配置分层；Workspace 值保留 owner 和版本。':
    'Feature definition, release stage, and allowed configuration layering; Workspace values retain owner and version.',
  功能配置: 'Function configuration',
  '加载中 fixture': 'Loading fixture',
  包含: 'contains',
  包括历史版本: 'Includes historical versions',
  '区分全局保护、服务策略、Workspace 配额和 provider 限制。':
    'Distinguish between global protection, service policies, Workspace quotas, and provider limits.',
  '区分服务定义、产品用途、owner 和实际连接实例。':
    'Distinguish between service definition, product purpose, owner, and actual connection instance.',
  '区分计量值、套餐权益和 owner 账单口径，不从调用量推断商业状态。':
    'Distinguish between measurement value, package rights and owner billing caliber, and do not infer business status from call volume.',
  '危险操作必须展示精确权限、影响范围、版本/当前性检查和受保护确认。':
    'Dangerous operations must demonstrate precise permissions, scope of impact, version/currentness checks, and protected confirmation.',
  即将到期: 'Expiring soon',
  即将过期: 'Expires soon',
  历史: 'History',
  历史版本: 'Historical version',
  '历史版本仅用于版本比较，不代表当前适用知识。':
    'Historical versions are only for version comparison and do not represent current applicable knowledge.',
  原因: 'Reason',
  原始产物写入: 'Original product writing',
  原始文件: 'Original file',
  去重后: 'After deduplication',
  去重身份: 'Remove duplicate identities',
  双人复核: 'Double review',
  双版本窗口: 'Dual version window',
  发布: 'Publish',
  发布权限: 'Publish permissions',
  发布版本: 'Release version',
  发布状态: 'Release status',
  发布阶段: 'Release stage',
  发布阶段未执行: 'Release phase not executed',
  发现: 'Discover',
  发票: 'Invoice',
  发票管理: 'Invoice management',
  发起会话处置: 'Initiate session processing',
  发起会话撤销: 'Initiate session revocation',
  发起凭证轮换: 'Initiate certificate rotation',
  发起套餐变更: 'Initiate package change',
  发起授权复核: 'Initiate authorization review',
  发起支付调查: 'Initiate payment investigation',
  取消: 'Cancel',
  '取消 RUN-9821': 'Cancel RUN-9821',
  受保护: 'protected',
  受信设备: 'Trusted device',
  受控取消: 'Controlled Cancellation',
  受配额限制: 'Subject to quota restrictions',
  受限: 'Restricted',
  受限开放: 'Restricted access',
  变更: 'Change',
  变更待生效: 'Change pending',
  另行配置: 'Configure separately',
  '只收集需要 Super Admin 判断的事项，按权限、截止时间和阻断影响排序。':
    'Only collect matters that require Super Admin judgment, sorted by permissions, deadlines, and blocking impact.',
  只读: 'Read only',
  只读投影: 'Read-only projection',
  '只读查看 owner 支付状态、provider reference 与 ledger receipt；支付不等于履约或接受。':
    'Read-only view of owner payment status, provider reference and ledger receipt; payment does not equal performance or acceptance.',
  只读运行参数: 'Read-only operating parameters',
  可委派: 'Delegable',
  可恢复: 'Recoverable',
  可恢复阶段: 'Recoverable stage',
  可查辖区: 'Jurisdiction can be checked',
  可检索文档: 'Searchable documents',
  可用: 'Available',
  '可用对象仍显示；缺失来源不会被折叠为空。':
    'Available objects are still shown; missing sources are not collapsed to empty.',
  可用性不是一个开关: 'Availability is not a switch',
  可用性策略: 'Availability strategy',
  可用率: 'Availability rate',
  可转换: 'Convertible',
  司法辖区: 'Jurisdiction',
  司法辖区推进: 'Jurisdictional advancement',
  合规检查: 'Compliance check',
  合规管理: 'Compliance Management',
  '名称、ID 或 owner': 'name, ID or owner',
  后续发布阶段未开始: 'The subsequent release phase has not started',
  含系统角色: 'Including system roles',
  '启动 Demo 评估': 'Start Demo evaluation',
  启用: 'Enable',
  '启用 Workspace': 'Enable Workspace',
  启用关系: 'Enable relationship',
  启用站点: 'Enable site',
  启用计划: 'Enable plan',
  告警: 'Alarm',
  告警调查上下文: 'Alarm investigation context',
  周期: 'Period',
  '品牌方 · United States': 'Brand · United States',
  响应期限: 'Response deadline',
  商业与支付: 'Business and Payment',
  商标价值评估: 'Trademark value assessment',
  商标申请与生命周期: 'Trademark application and life cycle',
  商标续展与监控: 'Trademark renewal and monitoring',
  四: 'Four',
  '四 24': 'Four 24',
  回归: 'Return',
  '回归 78%': 'Return to 78%',
  回滚就绪: 'Rollback ready',
  回滚点: 'Rollback point',
  '国家 / 地区': 'Country/Region',
  国际公告: 'International Announcement',
  图样: 'Pattern',
  '在本地 Demo 数据集中执行只读查询': 'Execute read-only queries in the local Demo dataset',
  '在本地 Demo 知识集中执行带引用检索':
    'Perform a reference search in the local Demo knowledge set',
  在线: 'Online',
  域名: 'Domain name',
  域名异常: 'Domain name exception',
  处理中: 'Processing',
  处理事项: 'Processing matters',
  处置: 'Disposal',
  备用路由: 'Alternate route',
  '复制对象 ID（本地）': 'Copy object ID (local)',
  复核: 'Review',
  复核证据高风险定位: 'Review high-risk positioning of evidence',
  '外部 API': 'External API',
  '外部 API 与集成': 'External APIs and Integration',
  外部服务: 'External services',
  '多 Workspace 用户': 'Multiple Workspace users',
  大小: 'size',
  失联: 'Lost contact',
  失败: 'Failed',
  '失败 / 已隔离': 'failed/isolated',
  失败与恢复: 'Failure and recovery',
  '失败于 09:36': 'failed at 09:36',
  失败执行: 'Failed execution',
  失败组: 'Failure Group',
  失败记录: 'Failure record',
  失败隔离: 'Failure isolation',
  套餐: 'Package',
  套餐上限: 'Package limit',
  套餐与权益: 'Packages and benefits',
  '套餐声明可获得的产品与功能范围；实际启用仍由 Workspace 配置决定。':
    'Plans declare the range of products and features available; actual enablement is still determined by Workspace configuration.',
  套餐权益: 'Package benefits',
  套餐管理: 'Package management',
  存储: 'Storage',
  存储与原始库存: 'Storage and original inventory',
  季度复核: 'Quarterly review',
  孤立角色: 'Isolated character',
  安全与审计: 'Security and Auditing',
  安全主体: 'Security Principal',
  安全事件: 'Security incident',
  安全事件与审计轨迹: 'Security events and audit trails',
  安全告警: 'Security Alert',
  '安全态势、权限策略、审计与高风险操作':
    'Security posture, permission policies, auditing and high-risk operations',
  安全总览: 'Safety Overview',
  完成: 'Complete',
  完整: 'Complete',
  完整性: 'Integrity',
  定位准确性: 'Positioning accuracy',
  实时告警: 'Real-time alarm',
  实时告警调查: 'Real-time alarm investigation',
  实现: 'Implementation',
  '实现 Profiles': 'Implement Profiles',
  实现谱系: 'Implement pedigree',
  实际健康: 'Actual health',
  审批: 'Approval',
  审查手册: 'Review Manual',
  '审核 CNIPA 冻结计划': 'Review of CNIPA Freeze Plan',
  审核历史: 'Audit history',
  审核并继续: 'Review and continue',
  审核结论: 'Audit conclusion',
  审核说明: 'Audit instructions',
  审核队列: 'Audit queue',
  审计: 'Audit',
  审计事件: 'Audit events',
  审计日志: 'Audit log',
  审阅产品启用变更: 'Review product enablement changes',
  审阅全局策略变更: 'Review global policy changes',
  审阅关系变更: 'Review relationship changes',
  审阅恢复条件: 'Review recovery conditions',
  审阅策略变更: 'Review policy changes',
  审阅计划变更: 'Review planned changes',
  审阅计量周期: 'Review measurement cycle',
  审阅路由变更: 'Review routing changes',
  审阅风险操作: 'Review risky operations',
  容量预警: 'Capacity warning',
  密钥与凭证: 'Keys and credentials',
  '对照 owner 计量、套餐包含量和超额候选；不从估算直接生成应收。':
    'Contrast owner metering, package inclusions, and excess candidates; do not generate receivables directly from estimates.',
  对象: 'Object',
  '对象 ID': 'Object ID',
  对象摘要: 'Object summary',
  对象数: 'Number of objects',
  对象类型: 'Object type',
  对账差异: 'Reconciliation differences',
  '导出 Manifest': 'Export Manifest',
  '导出 package manifest': 'Export package manifest',
  导出商业视图: 'Export business view',
  导出成本估算: 'Export cost estimate',
  导出所选运行证据: 'Export selected running evidence',
  导出演示产品用量: 'Export demo product usage',
  导出演示使用快照: 'Export demo usage snapshot',
  导出演示审计片段: 'Export demo audit clips',
  导出演示报表: 'Export demo report',
  导出演示收入投影: 'Export demo revenue projection',
  导出演示调用快照: 'Export demo call snapshot',
  导出脱敏日志片段: 'Export desensitization log fragments',
  导出脱敏活动记录: 'Export desensitization activity records',
  导出调用证据: 'Export call evidence',
  导出运行证据: 'Export running evidence',
  将到期: 'will expire',
  '将身份、Workspace、Membership 和角色作为独立对象展示其关系。':
    'Shows the relationship between Identity, Workspace, Membership and Role as independent objects.',
  尚未创建: 'has not been created yet',
  '尚未得到结果，不推断为空或健康。':
    'No results have been obtained yet, no null or health is inferred.',
  尚未执行: 'Not yet executed',
  尚未生成: 'has not been generated yet',
  尚未自动恢复: 'has not yet automatically restored',
  展开评审工具: 'Expand review tools',
  '展示 Workspace 对产品的权益、配置与健康；不替代产品全局发布状态。':
    'Shows Workspace’s rights, configuration, and health of the product; it does not replace the global release status of the product.',
  '展示 provider 计量、路由估算与预算；不作为财务 owner 账本。':
    "Displays provider metering, routing estimates and budgets; does not serve as the financial owner's ledger.",
  '展示 worker 能力、心跳、并发和租约，不由聚合后台伪造可用性。':
    'Exhibits worker capabilities, heartbeats, concurrency, and leases without faking availability by the aggregation backend.',
  履约: 'Performance',
  峰值低于容量阈值: 'The peak value is below the capacity threshold',
  '工作日 10:00': 'Working days 10:00',
  '工作日 10:00 CST': 'Weekdays 10:00 CST',
  工具: 'Tools',
  工具集成: 'Tool integration',
  已使用: 'used',
  已升级: 'Upgraded',
  已发布: 'Published',
  已启用: 'Enabled',
  '已复核 9': 'Reviewed 9',
  已完成: 'Completed',
  已对账: 'Reconciled',
  已封账: 'Account closed',
  '已展示受保护操作的 Demo 确认；未调用 owner API，也未产生生产变更。':
    'Demo confirmation of protected operation shown; no owner API was called, and no production changes were made.',
  已归档: 'Archived',
  已恢复告警: 'The alarm has been restored',
  已恢复的告警调查上下文: 'Restored alarm investigation context',
  已批准: 'Approved',
  已接受: 'Accepted',
  已控制: 'Controlled',
  已撤销: 'Canceled',
  已暂停: 'Paused',
  已更新: 'Updated',
  已确认: 'Confirmed',
  已签发: 'Issued',
  已覆盖: 'Overwritten',
  已解决: 'Resolved',
  已记录: 'Recorded',
  已载入演示数据: 'Demo data loaded',
  已过期: 'Expired',
  '已进入关联 owner 处理页面，未执行任何生产操作。':
    'has entered the associated owner processing page and has not performed any production operations.',
  '已连接 owner': 'Connected owner',
  已连接辖区: 'Jurisdiction connected',
  '已通知 owner': 'Notified owner',
  已配置: 'Configured',
  '已配置 · 不可见': 'Configured · Invisible',
  已阻断: 'Blocked',
  已隔离: 'Isolated',
  带宽: 'Bandwidth',
  带引用检索: 'Search with citation',
  带版本: 'with version',
  帮助: 'Help',
  帮助中心: 'Help Center',
  平台事件: 'Platform events',
  平台总览: 'Platform Overview',
  平台运行控制室: 'Platform operation control room',
  并发: 'Concurrency',
  并发已满: 'Concurrency is full',
  库存筛选: 'Inventory filter',
  延迟: 'Delay',
  '延迟 42 分钟': 'Delay 42 minutes',
  开启: 'Open',
  开放事件: 'Open events',
  开放故障: 'Open fault',
  开放案件: 'Open case',
  异常来源: 'Exception source',
  异常登录已阻断: 'Abnormal login has been blocked',
  当前: 'Currently',
  '当前 GA': 'Current GA',
  '当前 URL 未匹配已登记的 Super Admin 模块或页面，未回退显示其他业务内容。':
    'The current URL does not match the registered Super Admin module or page, and does not fall back to display other business content.',
  '当前主体不能查看该 owner 数据，页面未泄露对象详情。':
    'The current subject cannot view the owner data, and the page does not reveal the object details.',
  当前价格: 'Current price',
  当前套餐无退款管理权益: 'The current package has no refund management rights',
  '当前工作区使用明确标记的评审 fixture。':
    'The current workspace uses an explicitly marked review fixture.',
  当前影响: 'Current impact',
  当前性: 'Currentity',
  '当前性过滤 96%': 'Currentity filter 96%',
  当前无阻断问题: 'No blocking issues currently',
  当前版本: 'Current version',
  当前租约: 'Current lease',
  当前筛选没有对象: 'There are no objects in the current filter',
  '当前筛选返回 0 条 Demo 任务；详情和对象操作已清空。':
    'The current filter returns 0 Demo tasks; details and object operations have been cleared.',
  '当前筛选返回 0 条结果；详情和对象操作已清空。':
    'The current filter returns 0 results; details and object operations have been cleared.',
  影响: 'Influence',
  '影响 Workspace': 'Affects Workspace',
  影响范围: 'Scope of influence',
  '待 2 人': 'Wait for 2 people',
  '待 owner 处理': 'To be processed by owner',
  待人工处理: 'To be processed manually',
  待人工批准: 'Pending manual approval',
  待变更: 'To be changed',
  待变更申请: 'Pending change application',
  待处理事项: 'Pending items',
  待复核: 'To be reviewed',
  待审批计划: 'Plan pending approval',
  待审核: 'Pending review',
  待审核证据: 'Evidence to be reviewed',
  待我处理: 'Wait for me to deal with',
  待批准: 'Pending approval',
  待接受: 'To be accepted',
  待支付: 'To be paid',
  待生效版本: 'To be effective version',
  待确认: 'To be confirmed',
  待签发: 'To be issued',
  待补充: 'To be added',
  待评估: 'To be evaluated',
  待调整: 'To be adjusted',
  待调查: 'To be investigated',
  心跳有效: 'Heartbeat valid',
  必需: 'Required',
  必须核对外部回执: 'Must check external receipt',
  快速提取与分类: 'Quick extraction and classification',
  总用户: 'Total users',
  总览: 'Overview',
  恢复: 'Restore',
  恢复中: 'Recovering',
  恢复候选: 'Restore candidates',
  '恢复必须满足冻结计划、检查点、幂等和精确权限条件，不能只提供 Retry 按钮。':
    'Restore must meet freeze plan, checkpoint, idempotent, and precise permission conditions and cannot just provide a Retry button.',
  恢复码: 'Recovery code',
  成功: 'Success',
  '成功 fixture': 'Successful fixture',
  成功率: 'Success rate',
  '成功率 97.8%': 'Success rate 97.8%',
  成员: 'Member',
  成员关系: 'Membership',
  '成员关系由 Core 持有；同一身份可属于多个 Workspace，但每条 Membership 独立授权。':
    'Membership is held by Core; the same identity can belong to multiple Workspaces, but each Membership is independently authorized.',
  成员变更: 'Member changes',
  成员概况: 'Member profile',
  成本: 'Cost',
  成本分析: 'Cost analysis',
  成本流: 'Cost flow',
  手动上传原始文件: 'Manually upload original files',
  打开关联处理页面: 'Open the association processing page',
  打开导航: 'Open navigation',
  '执行 / 路由链': 'Execution/routing chain',
  执行任务: 'Perform tasks',
  执行只读查询: 'Execute read-only query',
  执行成功: 'Execution successful',
  执行权限: 'execution permission',
  执行记录: 'Execution record',
  批准证据: 'Approval evidence',
  批次: 'batch',
  批量商标监测: 'Batch trademark monitoring',
  '持有有效 lease': 'holds a valid lease',
  '按 Capability 和路由查看评估集、Critic、一致性与回归差异。':
    'View evaluation set, critic, consistency and regression differences by Capability and Route.',
  '按 Domain → Capability → Skill → Action 查看稳定结果契约、实现与证据覆盖。':
    'Press Domain → Capability → Skill → Action to view the stable result contract, implementation and evidence coverage.',
  '按 Payment 状态': 'Press Payment status',
  '按 Workspace': 'Press Workspace',
  '按 actor、对象、owner、Workspace 和 trace 查看不可变事件及版本差异。':
    'View immutable events and version differences by actor, object, owner, workspace, and trace.',
  '按 owner 隔离': 'Isolate by owner',
  '按 owner、任务类型、优先级和等待原因查看队列，不跨 owner 重排内部任务。':
    'View the queue by owner, task type, priority and wait reason, without reordering internal tasks across owners.',
  '按 trace、owner、级别和时间查询脱敏日志，并关联到任务和检查点。':
    'Query desensitization logs by trace, owner, level and time, and associate them with tasks and checkpoints.',
  '按产品展示 owner 计量和 Workspace 分布，不从用量推断支付或合同状态。':
    'Exhibits owner metering and Workspace distribution by product, without inferring payment or contract status from usage.',
  '按任务、区域、质量、延迟和预算选择 Primary 与 fallback，不隐藏降级。':
    'Select Primary and fallback by task, region, quality, delay and budget, without hiding fallback.',
  '按原支付、原因、证据、影响和 owner 决策管理退款/争议，不直接改写支付账本。':
    'Manage refunds/disputes based on the original payment, reasons, evidence, impact and owner decisions, without directly rewriting the payment ledger.',
  '按司法辖区汇总覆盖、任务推进和质量风险；异常不会被平均值隐藏。':
    'Aggregate coverage, mission advancement, and quality risk by jurisdiction; anomalies are not hidden by averages.',
  '按影响和可处理性归并告警，保留源事件、抑制规则与关联对象。':
    'Merge alarms according to impact and handleability, retaining source events, suppression rules and associated objects.',
  按影响隔离: 'Isolate by impact',
  按时间和执行阶段关联: 'Associated by time and execution phase',
  '按服务、Workspace、scope 和结果查看调用；用量不推断付款或授权。':
    'View calls by service, workspace, scope, and results; usage does not infer payments or entitlements.',
  '按来源、辖区和当前性检索可引用知识，结果始终携带精确 locator。':
    'Search citable knowledge by source, jurisdiction, and currency, with results always carrying the exact locator.',
  '按用户聚合其跨 Workspace 操作，但事件仍保留对象 owner 与 Workspace 上下文。':
    'Aggregate their cross-workspace operations by user, but events still retain the object owner and workspace context.',
  按策略: 'By strategy',
  按策略派发: 'Distributed according to strategy',
  '按组织类型、地区、订阅和生命周期管理 Workspace，并进入统一组织档案。':
    'Manage Workspaces by organization type, region, subscription, and lifecycle, and access unified organization profiles.',
  '按订单类型、Workspace、状态和时间查看商业意图、支付关联及完成 receipt。':
    'View business intent, payment associations, and completion receipts by order type, workspace, status, and time.',
  '按辖区与对象字段构造只读查询，并保留命中来源、版本与未命中的区别。':
    'Construct a read-only query based on jurisdiction and object fields, and retain the differences between hit sources, versions, and misses.',
  '按连接实例聚合失败、影响、降级与恢复证据，不将 provider 返回视为正式结论。':
    'Aggregates failure, impact, degradation, and recovery evidence by connection instance, and does not treat provider returns as formal conclusions.',
  按阶段重试: 'Retry by stage',
  按阶段隔离: 'Isolation by stage',
  授权: 'Authorization',
  排队: 'Queue',
  接受时间: 'Accept time',
  '接近 Workspace 配额': 'Close to Workspace quota',
  接近阈值: 'Close to threshold',
  控制项: 'Control',
  '提交 Brain 配置变更': 'Commit Brain configuration changes',
  '提交 Data Engine 配置变更申请': 'Submit a Data Engine configuration change request',
  提交优先级变更申请: 'Submit priority change request',
  提交变更申请: 'Submit change request',
  提交权限策略变更: 'Submit permission policy changes',
  提交配置变更: 'Commit configuration changes',
  提交配额调整: 'Submit quota adjustment',
  提交限流变更申请: 'Submit a current limit change application',
  '搜索 package ID 或辖区': 'Search package ID or jurisdiction',
  搜索当前模块: 'Search for the current module',
  搜索数据包: 'Search packets',
  搜索知识来源: 'Search for knowledge sources',
  搜索运行: 'Search run',
  操作: 'operation',
  操作记录: 'Operation record',
  支付成功: 'Payment successful',
  支付权限: 'Payment permissions',
  支付状态: 'Payment status',
  支付状态同步: 'Payment status synchronization',
  支付记录: 'Payment record',
  收入总览: 'Revenue Overview',
  收入流: 'Income stream',
  收入趋势与构成: 'Income trends and composition',
  收起评审工具: 'Collapse review tools',
  数据保留策略: 'Data retention policy',
  数据包: 'Data packet',
  数据包工作区: 'Data Packet Workspace',
  数据包质量校验: 'Packet quality check',
  数据包质量状态: 'Packet quality status',
  数据域运行总览: 'Data domain operation overview',
  数据新鲜度: 'Data freshness',
  数据查询: 'Data query',
  数据查询实验台: 'Data Query Experiment Bench',
  数据源: 'Data source',
  数据源连接: 'Data source connection',
  数据覆盖: 'Data coverage',
  数据覆盖与新鲜度: 'Data coverage and freshness',
  数据覆盖矩阵: 'Data coverage matrix',
  数据过期: 'Data expired',
  '整体观察与显著部分比较需要结合相关公众认知。':
    'Overall observation and comparison of significant parts need to be combined with relevant public awareness.',
  整体观察与显著部分的关系: 'The relationship between overall observation and significant parts',
  '整体评估显著性并保留商品、服务和适用范围。':
    'Evaluate overall significance and retain goods, services and scope of application.',
  文件: 'File',
  文件投递: 'File delivery',
  新任务已停止派发: 'New tasks have stopped being dispatched',
  '新鲜度 87%': 'Freshness 87%',
  '无 Critic': 'No Critic',
  无当前影响: 'No current impact',
  无成员: 'No members',
  '无数据 fixture': 'No data fixture',
  '无权限 fixture': 'No permission fixture',
  无紧急停用: 'No emergency deactivation',
  无自动批准: 'No automatic approval',
  无证据: 'No evidence',
  无读取权限: 'No read permission',
  无阻断: 'No blocking',
  日: 'day',
  '日 27': 'Day 27',
  日志流: 'Log stream',
  '时间范围：2012–至今': 'Time range: 2012–present',
  明日: 'Tomorrow',
  明确关系: 'Clear the relationship',
  明确禁止: 'Explicitly prohibited',
  星轨: 'Star Trail',
  '昨天 16:30': 'Yesterday 16:30',
  '昨天 23:20': 'Yesterday 23:20',
  显式原因: 'Explicit reason',
  显式状态: 'Explicit status',
  显式配置: 'Explicit configuration',
  智能编排: 'Intelligent orchestration',
  暂停: 'Pause',
  暂停关系: 'Suspend relationship',
  暂停扩展: 'Pause expansion',
  暂停来源: 'Pause source',
  暂未接入: 'Not yet connected',
  '更改只用于产品评审；保存会进入受保护确认。':
    'Changes are for product review only; saving will result in protected confirmation.',
  替代: 'instead',
  最多: 'most',
  最旧来源: 'Oldest source',
  '最近 12 个月': 'Last 12 months',
  '最近 5 分钟': 'Last 5 minutes',
  最近事件: 'Recent events',
  最近分区: 'Recent partition',
  最近发布: 'Recently published',
  最近握手: 'Recent handshake',
  最近活动: 'Recent activities',
  最近登录: 'Latest login',
  最近运行日志: 'Recent operation log',
  '最长 4m': 'Maximum 4m',
  最长等待: 'Longest wait',
  月: 'month',
  月活用户: 'Monthly active users',
  '有 Worker lease': 'Have Worker lease',
  '有 fallback receipt': 'has fallback receipt',
  '有 locator': 'has locator',
  '有 receipt': 'has receipt',
  有产品权益: 'has product rights',
  有原因: 'There is a reason',
  有审计记录: 'Have audit records',
  有批准记录: 'There is an approval record',
  有效: 'valid',
  '有效 lease': 'valid lease',
  有效授权: 'Valid authorization',
  有效期: 'Validity period',
  '有效至 2027-02': 'Valid until 2027-02',
  有效订阅: 'Active subscription',
  有权益: 'Have rights',
  有检查点: 'There are checkpoints',
  有版本: 'There is a version',
  有评估: 'With evaluation',
  有调查记录: 'There are investigation records',
  有迁移: 'There is migration',
  有迁移路径: 'There is a migration path',
  有降级路径: 'There is a downgrade path',
  服务定义: 'Service definition',
  '服务开关、授权、健康、限流与失败隔离':
    'Service switch, authorization, health, current limiting and failure isolation',
  服务节点: 'Service node',
  未作正式批准: 'Not formally approved',
  未公开: 'Unpublished',
  未分配: 'Not assigned',
  未启用: 'Not enabled',
  未建模: 'Not modeled',
  未开始: 'Not started',
  未执行: 'Not executed',
  未折叠为空: 'unfolded is empty',
  未探测: 'Not detected',
  '未接入或无权限的 owner 数据单独显示，不纳入健康率。':
    'Owner data that is not connected or has no permission is displayed separately and is not included in the health rate.',
  '未显示缓存结果；可模拟恢复页面展示状态。':
    'The cached results are not displayed; the page display state can be simulated to be restored.',
  未来日期: 'Future date',
  未来版本: 'Future versions',
  未正式批准: 'Not officially approved',
  未知: 'Unknown',
  未知来源: 'Unknown source',
  未知节点: 'Unknown node',
  未确认: 'Unconfirmed',
  未绑定: 'Unbound',
  未自动执行: 'is not executed automatically',
  未自动跳过: 'is not automatically skipped',
  未自动重试: 'did not automatically retry',
  未配置: 'Not configured',
  本周运行: 'Running this week',
  '本地 fixture 元数据；未读取对象存储或 owner API。':
    'Local fixture metadata; not read from object storage or owner API.',
  本月: 'This month',
  本月估算: 'This month’s estimate',
  本月确认: 'Confirmed this month',
  本月调用: 'Call this month',
  本次操作目标核对: 'Check the target of this operation',
  权利人: 'right holder',
  权益: 'Equity',
  权益覆盖: 'Equity coverage',
  权益规则: 'Equity rules',
  权限: 'Permissions',
  权限策略: 'Permission policy',
  权限配置: 'Permission configuration',
  条件: 'Conditions',
  条件满足: 'conditions are met',
  '条演示结果 ·': 'demo results ·',
  '条演示结果 · 本地确定性 fixture · 检索不会修改知识状态':
    'demo results · Local deterministic fixture · Retrieval does not modify the knowledge state',
  来源: 'Source',
  来源与权威边界: 'Source and authority boundaries',
  来源供应矩阵: 'Source supply matrix',
  来源关系: 'Source relationship',
  '来源到 Ready Package': 'Source to Ready Package',
  '来源到证据、审核与 Ready Package 的供应链':
    'Supply chain from source to evidence, audit and Ready Package',
  '来源名、ID 或类型': 'Source name, ID or type',
  来源当前性: 'Source currentness',
  来源新鲜度: 'Source freshness',
  来源版本: 'Source version',
  来源管理: 'Source management',
  来源说明: 'Source description',
  来自告警: 'from alert',
  '查看 Capability invocation、实现版本、输入/输出证据及关联 Brain/Execution 调用。':
    'View Capability invocation, implementation version, input/output evidence, and associated Brain/Execution invocations.',
  '查看 Data Engine': 'View Data Engine',
  '查看 Knowledge': 'View Knowledge',
  '查看 Workspace 对服务的精确 scope、授予人、到期和产品依据。':
    "View Workspace's precise scope, grantor, expiry, and product basis for the service.",
  '查看 owner 声明的节奏、下一次窗口和错过运行；这里只提交变更申请。':
    "View the owner statement's cadence, next window, and missed runs; only change requests are submitted here.",
  '查看产品版本、阶段、变更、回滚条件和 owner 部署证据。':
    'View product versions, phases, changes, rollback conditions, and owner deployment evidence.',
  查看元数据: 'View metadata',
  查看关系: 'View relationships',
  查看关联调用: 'View associated calls',
  查看分区: 'View partitions',
  '查看分层详情 →': 'View layering details →',
  查看演示日志: 'View demo log',
  查看演示证据: 'View demonstration evidence',
  '查看能力声明、心跳、并发和当前租约；聚合后台不伪造 heartbeat。':
    'View capability statements, heartbeats, concurrency, and current leases; the aggregation backend does not forge heartbeats.',
  '查看角色定义、授权范围和使用关系；权限来自 owner policy，不从 UI 名称推断。':
    'View role definition, authorization scope and usage relationship; permissions come from owner policy and are not inferred from UI name.',
  '查看订阅 owner 状态、续订窗口、套餐权益和变更历史；不在 UI 建立第二份订阅账本。':
    'Check the subscription owner status, renewal window, package rights and change history; do not create a second subscription ledger in the UI.',
  查看调查证据: 'View investigation evidence',
  '查看谱系 →': 'View pedigree →',
  '查看跨平台安全配置、版本和 owner；变更必须经过精确权限与影响审阅。':
    'View cross-platform security configuration, version, and owner; changes must be reviewed for precise permissions and impact.',
  '查看默认区域、保留、预算和安全策略；更改通过 owner 审批。':
    'View default zone, retention, budget, and security policies; changes are approved by owner.',
  查询值: 'Query value',
  查询字段: 'Query field',
  '查询词和来源筛选已执行；0 条结果不会显示预置命中。':
    'Query term and source filtering performed; 0 results will not show preset hits.',
  校验: 'Verification',
  校验摘要: 'Verification summary',
  '核对组件版本、只读运行参数与变更边界；配置变更由 owner 审批执行。':
    'Check the component version, read-only running parameters and change boundaries; configuration changes are approved and executed by the owner.',
  案件: 'Case',
  案件检索条件: 'Case search conditions',
  '检查一次执行的计划、阶段、Capability 调用、日志和最终 receipt。':
    'Check an execution plan, stages, capability calls, logs, and final receipt.',
  '检查包清单、内部文件、质量问题与可恢复阶段；包状态不等同于 Official Truth。':
    'Check package manifest, internal documentation, quality issues, and recoverability stages; package status does not equal Official Truth.',
  检查来源任务: 'Check source task',
  检查点: 'Checkpoint',
  '检查点已保留，尚未执行恢复':
    'The checkpoint has been retained and recovery has not been performed yet',
  '检查请求如何通过 guard、Capability、模型路由、工具与 Critic。':
    'Check how requests pass through guards, capabilities, model routing, tools, and critics.',
  检索: 'Search',
  模块启停: 'Module start and stop',
  模型: 'Model',
  模型管理: 'Model management',
  模型编排与降级路径: 'Model orchestration and downgrade path',
  模型路由: 'Model routing',
  '模型路由、智能编排、质量、延迟与成本':
    'Model routing, intelligent orchestration, quality, delay and cost',
  模型路由超时: 'Model routing timeout',
  '模拟刷新 Brain 快照': 'Simulate refreshing Brain snapshot',
  '模拟刷新 receipt': 'Simulate refresh receipt',
  模拟刷新依赖快照: 'Simulate refresh dependency snapshot',
  模拟刷新运行投影: 'Simulate refresh running projection',
  模拟恢复页面状态: 'Simulate recovery page status',
  模拟运行健康探针: 'Simulate running health probes',
  模拟页面状态: 'Simulate page status',
  '正在请求 owner projection': 'Requesting owner projection',
  正在读取: 'Reading',
  正常: 'Normal',
  正式发布: 'Officially released',
  '此处为 Demo fixture；身份、Workspace、产品、订阅和支付状态仍由各自 owner 持有。':
    'This is a Demo fixture; identity, workspace, product, subscription and payment status are still held by their respective owners.',
  '此聚合后台只提交带审计上下文的变更申请，不绕过 owner 配置治理。':
    'This aggregation background only submits change requests with audit context and does not bypass owner configuration governance.',
  '此详情来自明确标记的 Demo fixture。真实模式只能显示 owner 通过 Gateway 返回并通过权限检查的 projection。':
    'This detail comes from the explicitly marked Demo fixture. Real mode can only display owner projections returned through the Gateway and passing permission checks.',
  此预览不会执行生产操作: 'This preview will not perform production operations',
  '每 30 分钟': 'Every 30 minutes',
  '每 6 小时': 'Every 6 hours',
  每周一: 'Every Monday',
  '每日 01:00 UTC': 'Daily 01:00 UTC',
  '每日 02:00': 'Daily 02:00',
  '每日 02:00 UTC': 'Daily 02:00 UTC',
  '汇总 Payment/Billing owner 的收入投影、对账与未确认项；不是第二套财务账本。':
    "Summarizes the Payment/Billing owner's revenue projections, reconciliations, and unrecognized items; not a second set of financial ledgers.",
  '汇总安全事件、策略覆盖、权限变更与调查；未知状态不会显示为健康。':
    'Summarizes security events, policy coverage, permission changes, and investigations; unknown status will not be displayed as healthy.',
  '没有匹配的 Demo 数据源连接。': 'No matching Demo data source connection.',
  没有匹配的数据包: 'No matching packets',
  没有匹配的演示对象: 'No matching demo object',
  没有匹配的演示案件: 'No matching demo cases',
  没有匹配的演示知识: 'No matching demo knowledge',
  没有匹配的运行: 'No matching runs',
  没有直接保存: 'No direct saving',
  治理边界: 'Governance boundaries',
  治理锁定: 'Governance Lockdown',
  法人名称: 'Legal name',
  法规: 'Regulations',
  法规与指南: 'Regulations and Guidelines',
  法规文档: 'Regulatory documents',
  '法规文档 + locator': 'Regulatory documents + locator',
  活跃: 'Active',
  '活跃 Workspace': 'Active Workspace',
  活跃产品关系: 'Active product relationships',
  活跃会话: 'Active session',
  活跃成员: 'Active member',
  '派发 Knowledge 转换批次': 'Dispatch Knowledge conversion batch',
  派发转换: 'Dispatch conversion',
  测试与评估: 'Testing and Evaluation',
  测试连接: 'Test connection',
  海外供应商匹配: 'Overseas supplier matching',
  满足检查点条件: 'satisfies checkpoint conditions',
  漂移: 'Drift',
  演示安全态势: 'Demonstrate security posture',
  演示快照: 'Demo snapshot',
  演示成本: 'Demo cost',
  演示数据: 'Demo data',
  '演示数据 · 仅供产品评审，不连接生产写操作，不代表实时运行或 Official Truth':
    'Demo data · For product review only, not connected to production write operations, does not represent real-time operation or Official Truth',
  演示月收入: 'Demonstrate monthly income',
  演示状态: 'Demo status',
  演示理由: 'Demonstration reasons',
  演示编辑器: 'Demo Editor',
  '演示：一个 owner projection 已过期；其余数据保持可见并带来源。':
    'Demonstration: One owner projection has expired; remaining data remains visible and sourced.',
  熔断: 'Meltdown',
  版本: 'version',
  版本候选: 'Version candidate',
  版本偏差: 'Version deviation',
  版本化: 'Versioning',
  版本发布: 'version released',
  版本差异采集: 'Version difference collection',
  版本更新: 'Version update',
  版本管理: 'Version management',
  版本线: 'version line',
  状态: 'status',
  '状态模拟不代表 owner 的真实运行状态':
    'State simulation does not represent the real running state of owner',
  状态筛选: 'Status filter',
  '独立 owner': 'Independent owner',
  现在: 'Now',
  生成时间: 'Generation time',
  '生成本地 Demo 缺口清单': 'Generate local Demo gap list',
  生效: 'takes effect',
  生效版本: 'Effective version',
  用户: 'User',
  用户与权限: 'Users and permissions',
  用户活动: 'User activity',
  '用来源 × 辖区热力图观察 SLA、新鲜度和失败隔离，不把无数据误判为健康。':
    'Use source × jurisdiction heat map to observe SLA, freshness and failure isolation, and do not misjudge no data as healthy.',
  用途说明已更新: 'Usage description updated',
  '由 Billing owner': 'by Billing owner',
  '由 Brain owner': 'by Brain owner',
  '由 Payment owner 提供': 'Provided by Payment owner',
  '由 Trading owner': 'by Trading owner',
  申请人: 'Applicant',
  申请日: 'Application date',
  '申请隔离 Worker': 'Apply for isolation Worker',
  登录与安全: 'Login and security',
  登录事件: 'Login event',
  登录安全: 'Login security',
  登录风险: 'Login risk',
  '登记 Knowledge 来源': 'Register Knowledge source',
  登记工具候选: 'Register tool candidates',
  登记数据源: 'Register data source',
  登记服务申请: 'Registration service application',
  登记模型候选: 'Register model candidates',
  的调查上下文: 'investigation context',
  '目录以稳定结果契约为中心，并明确 Primary、Supporting 与 Critic 组合。':
    'The catalog is centered on the stable result contract and clearly defines the combination of Primary, Supporting and Critic.',
  目标: 'Target',
  '目标 95%': 'Target 95%',
  直接保存: 'Save directly',
  真实关系与来源: 'True relationship and source',
  '真实危险操作必须再次检查精确权限、对象版本、影响范围、理由、审批与审计。':
    'Really dangerous operations must be double-checked for precise permissions, object versions, scope of impact, justification, approval and auditing.',
  真实只读: 'True read-only',
  '真实只读 · 只会通过 Gateway、HttpOnly session 与精确 owner capability 读取':
    'True read-only · Will only read through Gateway, HttpOnly session and precise owner capability',
  真实只读运行摘要: 'True read-only running summary',
  '真实操作需要 exact owner command、权限、版本/当前性检查、原因、审批、幂等键与审计记录。':
    'Real operation requires exact owner command, permissions, version/currentness checks, reasons, approvals, idempotent keys and audit records.',
  知识供应总览: 'Knowledge Supply Overview',
  知识检索: 'Knowledge retrieval',
  知识检索词: 'Knowledge search terms',
  矩阵维度: 'Matrix dimensions',
  短信通知: 'SMS notification',
  确认后只显示本地演示反馈: 'Only display local demo feedback after confirmation',
  确认异常登录调查范围: 'Confirm abnormal login investigation scope',
  确认所选告警: 'Confirm the selected alarm',
  确认演示路径: 'Confirm demo path',
  租约剩余: 'Lease remaining',
  稳定: 'Stable',
  '稳定结果契约、版本谱系、实现与证据':
    'Stable result contract, version lineage, implementation and evidence',
  站点: 'site',
  章节版本: 'Chapter version',
  '等待 Gateway 完成身份、权限和 owner contract 校验。':
    'Wait for Gateway to complete identity, permission and owner contract verification.',
  '等待 Worker': 'Waiting for Worker',
  '等待 owner': 'Waiting for owner',
  '等待 receipt': 'Waiting for receipt',
  等待交付: 'Waiting for delivery',
  '等待兼容 Worker': 'Waiting for compatible Worker',
  等待剩余页面: 'Wait for remaining pages',
  等待受控恢复: 'Waiting for controlled recovery',
  等待复核: 'Waiting for review',
  等待审批: 'Waiting for approval',
  等待审核: 'Waiting for review',
  等待批准: 'Waiting for approval',
  等待权限: 'Waiting for permission',
  等待派发: 'Waiting for dispatch',
  等待证据审核: 'Waiting for evidence review',
  等待评审: 'Waiting for review',
  等待转换: 'Waiting for conversion',
  策略: 'Strategy',
  '策略 v12': 'Strategy v12',
  '策略 v18': 'Strategy v18',
  '策略 v24': 'Strategy v24',
  策略冲突: 'Strategy conflict',
  策略命中后会话被撤销: 'The session was revoked after the policy hit',
  策略执行: 'Strategy execution',
  策略覆盖: 'Policy override',
  筛选当前列表: 'Filter the current list',
  '管理 Prompt 模板、变量、适用 Capability、版本与评估证据。':
    'Manage Prompt templates, variables, applicable Capabilities, versions and evaluation evidence.',
  '管理 Workspace 拥有的站点关系、域名、发布状态和内容 owner 健康。':
    'Manage Workspace-owned site relationships, domain names, publishing status, and content owner health.',
  '管理 manifest、交付目标、receipt 与对账状态；Ready 不等于下游接受或正式生效。':
    'Manage manifest, delivery target, receipt and reconciliation status; Ready does not mean downstream acceptance or official effect.',
  '管理 provider/owned model 的能力、区域、数据策略、评估和路由引用。':
    "Manages a provider/owned model's capabilities, regions, data policies, evaluations, and routing references.",
  '管理发票请求、签发、交付和作废链路，金额来自 owner 订单与税务上下文。':
    'Manage invoice request, issuance, delivery and voiding links with amounts from owner orders and tax context.',
  '管理套餐商业定义、价格版本和权益引用；权益内容由 Product owner 版本化。':
    'Manage package business definitions, price versions, and benefit references; benefit content is versioned by the Product owner.',
  '管理工具契约、作用域、实现版本和调用证据，外部保护动作仍需审批。':
    'Manage tool contract, scope, implementation version and call evidence, external protection actions still need to be approved.',
  '管理来源批准、启用状态、采集边界和关系图；来源登记不自动进入正式知识。':
    'Manage source approvals, enabled status, collection boundaries, and diagrams; source registration does not automatically enter formal knowledge.',
  '管理精确权限、条件、影响范围和版本；策略名不能替代权限检查结果。':
    'Manage precise permissions, conditions, scope of impact, and versions; policy names cannot replace permission check results.',
  '管理连接方式、抓取节奏和凭证存在性；密钥值永不在此页回显。':
    'Manages connection methods, crawl cadence, and credential existence; key values ​​are never echoed on this page.',
  '类似商品判断应结合功能、用途、销售渠道及相关公众的一般认知。':
    'The judgment of similar products should be based on functions, uses, sales channels and the general awareness of the relevant public.',
  '精确 capability': 'Exact capability',
  '精确 locator': 'Exact locator',
  '精确控制谁可发现、调用、评估和发布 Capability；调用权限不等于保护动作批准。':
    'Precisely control who can discover, call, evaluate, and publish capabilities; calling permissions does not equal protection action approval.',
  精确权限检查: 'Exact permission check',
  系统日志: 'System log',
  系统设置: 'System settings',
  系统配置: 'System configuration',
  繁忙: 'Busy',
  级别: 'level',
  组件: 'Component',
  组件与版本: 'Components and versions',
  组件版本: 'Component version',
  '组织、订阅、配额、产品与站点的全局管理':
    'Global management of organizations, subscriptions, quotas, products and sites',
  组织关系: 'Organizational relations',
  组织管理概览: 'Organizational Management Overview',
  '组装 Package': 'Assembly Package',
  '经 Gateway 和精确 Data read capability 获取；不重建 owner 任务或管理状态。':
    'Obtained via Gateway and precise Data read capability; does not rebuild owner task or management state.',
  结束上下文: 'End context',
  结果: 'Results',
  '结果只来自本地 Demo 数据集，不是 owner 实时查询或平台 Official Truth。':
    'The results only come from the local Demo data set, not the owner real-time query or the platform Official Truth.',
  '结果等待 Workplace 接受': 'The result is waiting for acceptance by Workplace',
  续订窗口: 'Renewal window',
  编排: 'Arrangement',
  '编排来源、频率、输出与允许的抓取边界；启停计划是受保护的 owner 操作。':
    'Orchestrates sources, frequencies, outputs, and allowed crawl boundaries; start-stop schedules are protected owner operations.',
  编排模板: 'Arrangement template',
  编排策略: 'Organization strategy',
  '缺 18h': 'missing 18h',
  '缺 locator': 'Missing locator',
  缺口: 'Gap',
  '缺失 ≠ 零': 'missing ≠ zero',
  '缺少安全 API': 'Missing security API',
  '缺少已选择并可由 Core 校验的 Workspace 上下文。':
    'There is a missing Workspace context that has been selected and can be verified by Core.',
  缺少精确读取权限: 'Missing precise read permissions',
  聚合层不修账: 'The aggregation layer does not repair accounts',
  '聚合模型、路由、执行、质量、延迟与成本；不把模型输出提升为正式状态。':
    'Aggregates model, routing, execution, quality, latency, and cost; does not promote model output to formal status.',
  能力: 'Ability',
  能力契约: 'Ability Contract',
  能力总览: 'Ability overview',
  能力目录: 'Competency Catalog',
  能力谱系与实现证据: 'Capability pedigree and implementation evidence',
  脱敏字段: 'Desensitization field',
  自动放宽: 'Auto-relaxation',
  自定义: 'Custom',
  节奏: 'Rhythm',
  范围: 'range',
  草稿: 'Draft',
  获客与服务入口: 'Customer acquisition and service entrance',
  表单: 'Form',
  被抑制: 'is suppressed',
  被限流: 'is restricted',
  裁决: 'Judgment',
  覆盖: 'override',
  覆盖缺口: 'Cover the gap',
  覆盖辖区: 'Covered jurisdictions',
  观察: 'Observation',
  '观察 PostgreSQL、ClickHouse 与 raw inventory 的容量、分区和保留策略；不提供聚合层删除。':
    'Observe the capacity, partitioning and retention policies of PostgreSQL, ClickHouse and raw inventory; aggregation layer deletion is not provided.',
  规则可追溯: 'Rules are traceable',
  规范化: 'Normalization',
  角色: 'Character',
  角色与权限: 'Roles and permissions',
  计划冲突: 'Planning conflict',
  计费确认: 'Billing confirmation',
  计量周期: 'Measuring cycle',
  订单: 'Order',
  订单投影延迟: 'Order projection delay',
  '订单投影延迟，不改变账本': 'Order projection is delayed and the ledger is not changed',
  '订单状态仍以 owner 账本为准': "The order status is still subject to the owner's ledger",
  订单管理: 'Order management',
  订阅: 'Subscribe',
  '订阅、订单、支付、发票与争议的 owner 视图':
    'owner view of subscriptions, orders, payments, invoices and disputes',
  订阅与套餐: 'Subscriptions and Packages',
  记录: 'Record',
  记录通过率: 'Record pass rate',
  设置分组: 'Set grouping',
  '访问与 owner 边界': 'Access and owner boundaries',
  访问违规: 'Access violation',
  证据: 'Evidence',
  证据与相关调用: 'Evidence and related calls',
  证据存在: 'Evidence exists',
  证据审核: 'Evidence review',
  证据当前: 'Evidence current',
  证据摘要生成: 'Evidence summary generation',
  证据集: 'Evidence set',
  评估: 'Evaluation',
  评估套件: 'Evaluation Kit',
  评估集: 'Evaluation set',
  '该投影未提供 freshness SLA': 'This projection does not provide a freshness SLA',
  '该页面尚无已批准的 Gateway 只读 projection。':
    'This page does not yet have an approved Gateway read-only projection.',
  '详情与对象操作已清空。': 'Details and object operations have been cleared.',
  误报候选: 'False positive candidate',
  '请求已成功，调整筛选条件可查看其他对象。':
    'The request was successful, adjust the filter conditions to view other objects.',
  读取超时: 'Read timeout',
  '读取超过本地等待时限。': 'The read exceeded the local waiting time limit.',
  读取边界: 'Read boundary',
  调度: 'Scheduling',
  调度日历: 'Scheduling Calendar',
  调度计划: 'Scheduling plan',
  '调整搜索词或状态筛选。': 'Adjust search terms or status filters.',
  '调整搜索词查看其他 fixture。': 'Adjust the search terms to view other fixtures.',
  调查中: 'Under investigation',
  调查时间线: 'Investigation timeline',
  调用: 'call',
  调用主体: 'Calling body',
  调用流: 'Call flow',
  调用统计: 'Call statistics',
  财务状态: 'Financial status',
  '财务状态只来自对应 owner；Payment 不是履约、权威、接受或完成。':
    'Financial status only comes from the corresponding owner; Payment is not performance, authority, acceptance, or completion.',
  财务账本: 'Financial ledger',
  账单: 'Bill',
  '账号、组织关系、角色授权与登录安全':
    'Account, organizational relationship, role authorization and login security',
  账户菜单: 'Account menu',
  质量: 'Quality',
  '质量状态来自 Demo fixture；不在聚合后台直接改写。':
    'The quality status comes from the Demo fixture; it is not directly rewritten in the aggregation background.',
  质量评估: 'Quality assessment',
  质量问题: 'Quality issues',
  质量问题未自动接受: 'Quality issues not automatically accepted',
  资源: 'Resources',
  资源配额: 'Resource quota',
  超出权益: 'Excess of equity',
  '超过 SLA 2h': 'Exceeded SLA 2h',
  超额保护: 'Excess protection',
  超额候选: 'Excess candidates',
  '跨 11 个地区': 'Across 11 regions',
  '跨 4 个 owner': 'spans 4 owners',
  '跨 4 个辖区': 'Across 4 jurisdictions',
  '跨 8 owner': 'spans 8 owners',
  '跨 Workspace': 'Cross Workspace',
  '跨 owner': 'Cross owner',
  '跨 owner 查看 durable run、租约、检查点和需要人工决策的执行。':
    'View durable runs, leases, checkpoints, and executions requiring human decision-making across owners.',
  '跨 owner 的平台运行态势与待处理事项':
    'Cross-owner platform operation status and pending matters',
  跨产品使用情况: 'Cross-product usage',
  跨时区: 'Across time zones',
  跨组织关系: 'Inter-organizational relationships',
  路径: 'path',
  路由: 'routing',
  路由策略: 'Routing strategy',
  跳到主要内容: 'Skip to main content',
  身份: 'Identity',
  身份与关系概览: 'Identity and Relationships Overview',
  身份仍存在: 'Identity still exists',
  身份状态: 'Identity status',
  转换: 'Conversion',
  转换处理: 'Conversion processing',
  转换队列等待: 'Conversion queue waiting',
  轮换中: 'In rotation',
  '输入、辖区和查询字段已执行；0 条结果不会回退到预置对象。':
    'Input, jurisdiction, and query fields implemented; 0 results will not fall back to provisioned objects.',
  输出: 'output',
  辖区: 'Jurisdiction',
  迁移: 'Migration',
  '过去 1 小时': 'Last 1 hour',
  '过去 24 小时': 'Last 24 hours',
  '过去 24h': 'Last 24h',
  '过去 30 分钟': 'Last 30 minutes',
  '过去 30 天': 'Last 30 days',
  过宽候选: 'Too wide candidate',
  过期单列: 'Expired single column',
  过滤结果: 'Filter results',
  '运行 18m 42s': 'Run 18m 42s',
  '运行 7m 12s': 'Run 7m 12s',
  '运行 Demo 评估': 'Run Demo evaluation',
  '运行 ID / 任务名': 'Run ID / task name',
  运行与任务: 'Run and task',
  运行中: 'Running',
  运行任务: 'Run the task',
  运行健康: 'Run healthy',
  运行健康与依赖: 'Run health and dependencies',
  运行只读来源评估: 'Run read-only source evaluation',
  '运行探针与业务成功率分开呈现，并标明故障影响和已配置降级路径。':
    'Running probes and business success rates are presented separately, and the impact of the fault and the configured degradation path are indicated.',
  运行控制室: 'Operation control room',
  运行正常: 'runs normally',
  运行状态: 'Running status',
  运行降级: 'Run downgrade',
  '返回 Demo 评审': 'Return to Demo review',
  返回告警调查: 'Return to alarm investigation',
  返回平台总览: 'Return to platform overview',
  返回当前真实控制台: 'Returns the current real console',
  返回数据不可信: 'The returned data is not trustworthy',
  '这是证据供应审核，不是 Capability 验证或 canon mutation。':
    'This is an evidence supply review, not a Capability verification or canon mutation.',
  '这里只管理产品级全局可用策略，不替代套餐权益、Workspace 配置或运行健康。':
    'This only manages product-level globally available policies and does not replace package benefits, Workspace configuration or running health.',
  进入受保护操作: 'Enter protected operation',
  进度: 'Progress',
  连接健康: 'Connect for Health',
  连接健康失败: 'Connection health failed',
  '连接失败 fixture': 'Failed to connect fixture',
  连接实例: 'Connection instance',
  连接类型: 'Connection type',
  连接配置: 'Connection configuration',
  '追踪 Outcome Contract、实现、Skill、Agent、评估和受控迁移谱系。':
    'Track Outcome Contract, implementation, Skill, Agent, evaluation and controlled migration lineage.',
  '追踪不可变原件、重复关系、来源版本与转换资格；替换会创建新版本。':
    'Track immutable originals, duplicate relationships, source versions, and conversion eligibility; substitutions create new versions.',
  '追踪邀请目标、Workspace、预期角色、有效期和接受结果，避免提前创建正式 Membership。':
    'Track invitation targets, workspaces, expected roles, expiration dates, and acceptance outcomes to avoid creating formal memberships in advance.',
  退回修订: 'Return revision',
  退款与争议: 'Refunds and Disputes',
  逐条决策: 'Decision-by-item',
  '逐条核对原文定位、转换结果和审核历史；批准不会自动改变 Capability 或平台 canon。':
    'Check original text positioning, conversion results, and review history item by item; approval does not automatically change Capability or platform canon.',
  '逐次查看输入 guard、Capability 调用、路由选择、provider receipt 与 Critic 结果。':
    'Check the input guard, capability call, routing, provider receipt and critic results one by one.',
  '通用分析 · 多模态': 'Universal analysis · Multimodal',
  通知: 'Notice',
  通知中心: 'Notification Center',
  '通知改走 Email': 'Notification changed to Email',
  通过: 'Passed',
  '通过 94%': 'Passed 94%',
  通过资格检查: 'Passed qualification check',
  通过输入检查: 'Check by input',
  逾期: 'Overdue',
  邀请: 'Invitation',
  '邀请 Workspace 成员': 'Invite Workspace members',
  邀请人: 'Inviter',
  邮件与协作: 'Mail and collaboration',
  部分: 'part',
  部分可用: 'Partially available',
  '部分可用 fixture': 'Some available fixtures',
  部分数据不可用: 'Some data is not available',
  部分来源不可用: 'Some sources are not available',
  部分覆盖: 'Partial coverage',
  配置策略: 'Configuration strategy',
  配置项: 'Configuration items',
  配额: 'Quota',
  配额使用: 'Quota usage',
  配额对象: 'Quota object',
  配额预警: 'Quota warning',
  采集: 'Collection',
  采集计划: 'Collection plan',
  采集速度降低: 'Collection speed decreased',
  重复: 'Repeat',
  重复项: 'Duplicates',
  重置: 'Reset',
  重试: 'Retry',
  重试只读请求: 'Retry the read-only request',
  金额: 'Amount',
  错过: 'missed',
  错过运行: 'Missed run',
  长文本与证据分析: 'Long text and evidence analysis',
  闲置商标交易: 'Idle trademark transactions',
  队列: 'Queue',
  队列项: 'Queue item',
  阶段: 'stage',
  阶段与检查点: 'Phases and checkpoints',
  阻断: 'Block',
  '阻断 CN 发布阶段': 'Block the CN release phase',
  阻断候选: 'Blocking candidates',
  降级: 'Downgrade',
  降级完成: 'Downgrade completed',
  降级节点: 'Downgrade node',
  降级调用: 'Downgrade call',
  限制: 'Restrictions',
  限流策略: 'Current limiting strategy',
  限流配置: 'Current limiting configuration',
  隔离: 'Isolation',
  隔离中: 'Isolated',
  隔离连接: 'Isolate connection',
  集成健康与影响范围: 'Integrated health and sphere of influence',
  集成服务: 'Integration services',
  集成服务目录: 'Integration Service Catalog',
  需人工修复: 'Needs manual repair',
  需修正: 'Needs correction',
  需关注: 'Need attention',
  '需关注 86%': 'Requires attention 86%',
  需内部处理: 'Requires internal processing',
  需回应: 'Response required',
  需处理: 'needs to be processed',
  需复核: 'Needs review',
  '需要 Workspace 上下文': 'Requires Workspace context',
  '需要 data-admin:approve': 'requires data-admin:approve',
  '需要 knowledge-review:approve': 'requires knowledge-review:approve',
  '需要 pdf-evidence-v3 能力': 'Requires pdf-evidence-v3 capability',
  '需要 security-investigation:read': 'requires security-investigation:read',
  需要一次批准: 'Requires one approval',
  需要处理: 'Needs processing',
  需要登录: 'Requires login',
  需要资深审核: 'Requires senior review',
  需调查: 'Needs investigation',
  非用户副本: 'Non-user copy',
  非真实账本: 'Unreal ledger',
  非财务账本: 'Non-financial ledger',
  非账单事实: 'Non-billing facts',
  非账本: 'Non-ledger',
  页面不存在: 'Page does not exist',
  '页面不存在 · Super Admin V2': 'Page does not exist · Super Admin V2',
  项: 'items',
  预期角色: 'Intended role',
  预演主要操作: 'Preview the main operations',
  预算: 'Budget',
  预算使用: 'Budget usage',
  '预算阈值剩余 26%': 'Budget threshold remaining 26%',
  风险: 'Risk',
  风险上限: 'Risk cap',
  风险会话: 'Risk Session',
  风险命中: 'Risk hit',
  风险操作: 'Risk operations',
  风险标记: 'Risk mark',
  验证中: 'Verifying',
  高: 'High',
  高权限: 'High authority',
  高风险: 'High risk',
  高风险操作: 'High risk operations',
  高风险登录已阻断: 'High-risk logins have been blocked',
  默认: 'Default',
  '＋ 创建任务': '+ Create task',
  '＋ 创建计划': '+ Create plan',
  '＋ 受保护操作': '+ protected operation',
  '＋ 登记数据源': '+ Register data source',
  '＋ 登记来源': '+ registration source'
} as const;

export type GeneratedEnglishSource = keyof typeof GENERATED_EN_US;
